/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function activeWindow(): ActiveWindow | null

export interface ActiveWindow {
  title?: string
  appName: string
  appPath?: string
  x: number
  y: number
  width: number
  height: number
  onMenu: boolean
}

export declare function clearDeadKey(): void

export declare function elementAtPoint(x: number, y: number): Promise<UiElement | null>

export interface ElementNode {
  role?: string
  name?: string
}

export interface ElementRect {
  x: number
  y: number
  width: number
  height: number
}

export declare function focusedElement(): Promise<UiElement | null>

export interface HookEvent {
  kind: string
  button: number
  x: number
  y: number
  clicks: number
  keycode: number
  shift: boolean
  ctrl: boolean
  alt: boolean
  meta: boolean
}

export declare function isSupported(): boolean

export declare function keyLabel(keycode: number): string | null

export declare function releaseWebContent(): void

export declare function resolveKey(keycode: number, shift: boolean, ctrl: boolean, alt: boolean): string | null

export declare function startInputHook(callback: (event: HookEvent) => void): void

export interface UiElement {
  role?: string
  name?: string
  automationId?: string
  value?: string
  helpText?: string
  isPassword: boolean
  valueLength?: number
  rect?: ElementRect
  ancestors: Array<ElementNode>
  children: Array<ElementNode>
}

export declare function windowAt(x: number, y: number): ActiveWindow | null
